// Receptionist character profiles powering the "Meet your receptionist"
// section on the homepage, the industry-page avatar cards, and the
// /receptionist/[slug] profile pages.
//
// One source of truth, keep this file flat and JSON-shaped so non-developers
// can tweak copy without touching component code.

export type ChatRole = 'caller' | 'agent' | 'agent_upsell'

export interface ChatLine {
  role: ChatRole
  text: string
}

export interface Receptionist {
  slug: string
  name: string
  industry: string
  industrySlug: string             // matches /industries/[slug] where one exists
  tagline: string
  bgColor: string                  // accent + avatar fallback colour
  teaserBullets: string[]          // 3 bullets for the homepage card
  knowledgeBullets: string[]       // 8 to 10 bullets for the full profile page
  sampleChat: ChatLine[]
  heroCTA: string                  // e.g. "Hire Bella"
  pricingLink: string              // always '/pricing'
}

export const RECEPTIONISTS: Receptionist[] = [
  {
    slug: 'bella',
    name: 'Bella',
    industry: 'Restaurants and Takeaway',
    industrySlug: 'restaurants',
    tagline: 'Bella never misses an order. Even at 8pm on a Friday.',
    bgColor: '#E8622A',
    teaserBullets: [
      'Takes full orders with modifications and customisations',
      'Upsells sides, drinks, and upgrades on every call',
      'Handles delivery zones, ETAs, and dietary questions',
    ],
    knowledgeBullets: [
      'Takes full orders including modifications, exclusions, and customisations',
      'Knows the difference between pickup, delivery, and dine-in orders',
      'Always confirms the name on the order and the pickup or delivery time',
      'Knows to ask for a delivery address and check it falls within your delivery zone',
      'Upsells sides, drinks, and meal deals on every single call without fail',
      'Handles dietary questions, vegetarian, vegan, gluten free, nut allergies',
      'Knows your opening hours, specials, and minimum delivery order',
      'Sends SMS confirmation to every caller automatically after the order',
      'Handles "how long will it be" questions with accurate ETAs',
      'Transfers complex complaints to the owner immediately',
    ],
    sampleChat: [
      { role: 'caller', text: 'Hi, can I get an order for delivery?' },
      { role: 'agent', text: "Of course! What's the delivery address?" },
      { role: 'caller', text: '14 Palm Avenue, Burleigh Heads.' },
      { role: 'agent', text: "Perfect, that's within our delivery zone. What can I get started for you?" },
      { role: 'caller', text: 'Two large fish and chips and a chicken burger please.' },
      { role: 'agent_upsell', text: 'Great choice. Can I add drinks to that? We have Coke, Lemonade, and Sprite for $3.50 each.' },
      { role: 'caller', text: 'Two Cokes thanks.' },
      { role: 'agent', text: "Done. That's $59.50 and about 35 minutes for delivery. What name is this under?" },
    ],
    heroCTA: 'Hire Bella',
    pricingLink: '/pricing',
  },
  {
    slug: 'troy',
    name: 'Troy',
    industry: 'Towing and Transport',
    industrySlug: 'towing',
    tagline: 'Troy takes dispatch calls 24/7 so you can focus on the road.',
    bgColor: '#1565C0',
    teaserBullets: [
      'Knows to ask if a forklift is electric or gas',
      'Captures vehicle make, model, year, and breakdown location',
      'Sends job ID and ETA confirmation via SMS automatically',
    ],
    knowledgeBullets: [
      'Captures vehicle make, model, year, and registration on every call',
      'Knows to ask if a 4WD needs recovery points or snatch strap access',
      'Knows to ask if a forklift is electric or gas, and if gas whether it includes a gas bottle',
      'Knows to ask if an electric forklift comes with its charger',
      'Asks about excavator attachments, buckets, tilts, augers, thumbs',
      'Captures the exact breakdown location with cross-street or nearest landmark',
      "Describes the issue clearly, won't start, flat tyre, accident damage, requires tilt tray",
      'Gives callers an accurate ETA based on driver availability',
      'Sends job ID and ETA confirmation via SMS automatically after booking',
      'Knows the difference between a standard tow, a flatbed, and a tilt tray job',
    ],
    sampleChat: [
      { role: 'caller', text: "Hi, I need a tow. My forklift won't start." },
      { role: 'agent', text: 'No problem, we can help. Is it an electric forklift or gas?' },
      { role: 'caller', text: "It's gas." },
      { role: 'agent', text: 'Got it. Does it come with a gas bottle or do you supply your own?' },
      { role: 'caller', text: "It has its own bottle but I think it's run out." },
      { role: 'agent_upsell', text: 'Understood. We can bring a bottle as well if needed, just let us know. What\'s the address and what make is the forklift?' },
      { role: 'caller', text: "It's a Toyota 7FG25, at 14 Industrial Drive Yatala." },
      { role: 'agent', text: "Booked. Closest driver is about 22 minutes away. Job ID TW-4821. You'll get an SMS shortly." },
    ],
    heroCTA: 'Hire Troy',
    pricingLink: '/pricing',
  },
  {
    slug: 'charlotte',
    name: 'Charlotte',
    industry: 'Real Estate',
    industrySlug: 'real-estate',
    tagline: 'Charlotte qualifies every buyer so you only talk to the serious ones.',
    bgColor: '#8B5CF6',
    teaserBullets: [
      'Qualifies buyers on budget and pre-approval status',
      'Books inspection times and sends SMS confirmations',
      "Handles enquiries during open homes when you can't answer",
    ],
    knowledgeBullets: [
      'Asks every buyer about their budget range and preferred suburbs',
      'Qualifies whether they are pre-approved, saving, or just browsing',
      'Knows the difference between a buyer, a renter, a vendor, and an investor',
      'Books inspection times and sends SMS confirmation to every attendee',
      'Takes enquiries during open homes when you are with another buyer',
      'Handles after-hours property enquiries so no lead goes to voicemail',
      'Asks about property preferences, bedrooms, bathrooms, land size, features',
      'Captures timeline, buying now, 3 months, 6 months, just researching',
      'Handles rental enquiries including preferred lease start date and pet questions',
      'Flags pre-approved buyers immediately so you can call them back first',
    ],
    sampleChat: [
      { role: 'caller', text: "Hi, I'm calling about the property at 42 Palm Avenue." },
      { role: 'agent', text: 'Great property. Are you looking to buy or just making an enquiry?' },
      { role: 'caller', text: "Looking to buy. We've been pre-approved up to $850,000." },
      { role: 'agent_upsell', text: "Excellent, you're well within range for that one. The next inspection is Saturday at 10am. Would you like me to book you in?" },
      { role: 'caller', text: 'Yes please.' },
      { role: 'agent', text: 'Done. Can I get your name and mobile for the confirmation SMS?' },
      { role: 'caller', text: 'Sarah Mitchell, 0412 555 888.' },
      { role: 'agent', text: "Perfect Sarah. You'll get a confirmation text shortly. See you Saturday at 10." },
    ],
    heroCTA: 'Hire Charlotte',
    pricingLink: '/pricing',
  },
  {
    slug: 'jake',
    name: 'Jake',
    industry: 'Trades and Services',
    industrySlug: 'trades',
    tagline: "Jake captures every job enquiry even when you're on the tools.",
    bgColor: '#059669',
    teaserBullets: [
      'Triages emergency vs standard jobs instantly',
      'Asks the right questions before booking a call-back',
      'Handles pricing enquiries without committing to a quote',
    ],
    knowledgeBullets: [
      'Triages emergency vs urgent vs standard jobs immediately on every call',
      'Asks for the property address and a description of the issue',
      'Knows not to commit to a price without a site inspection',
      'Handles "how much does it cost" questions professionally without quoting',
      "Books specific call-back windows so callers aren't waiting all day",
      'Asks whether the caller is a homeowner, tenant, or property manager',
      'Captures the best contact number and time to call back',
      'Handles after-hours emergency calls and flags them to the owner immediately',
      "Knows to ask if there's safe access to the property",
      'Sends a confirmation SMS with the call-back window after every booking',
    ],
    sampleChat: [
      { role: 'caller', text: "Hi, I've got a burst pipe under my kitchen sink. It's flooding." },
      { role: 'agent', text: "That's urgent, we can get someone to you. Is the water shut off at the mains?" },
      { role: 'caller', text: "No I don't know where it is." },
      { role: 'agent_upsell', text: "Okay, find your water meter outside, usually near the front boundary, and turn it off now. I'll get a plumber to you within the hour. What's your address?" },
      { role: 'caller', text: '14 Coral Drive, Palm Beach.' },
      { role: 'agent', text: 'On the way. Can I get your name and mobile for updates?' },
      { role: 'caller', text: 'Mark, 0412 345 678.' },
      { role: 'agent', text: "Thanks Mark. You'll get an SMS when the plumber is 30 minutes away." },
    ],
    heroCTA: 'Hire Jake',
    pricingLink: '/pricing',
  },
  {
    slug: 'grace',
    name: 'Grace',
    industry: 'Healthcare and Clinics',
    industrySlug: 'healthcare',
    tagline: 'Grace keeps your appointment book full and your reception phone quiet.',
    bgColor: '#EC4899',
    teaserBullets: [
      'Books, reschedules, and cancels appointments',
      'Knows when to transfer urgent calls immediately',
      'Handles new vs existing patient enquiries correctly',
    ],
    knowledgeBullets: [
      'Books, reschedules, and cancels appointments without tying up reception staff',
      'Asks whether the caller is a new or existing patient',
      'Knows to ask which practitioner they prefer and whether any time suits',
      'Handles bulk billing questions accurately based on your billing policy',
      'Knows what to bring to a first appointment',
      'Never gives clinical advice under any circumstances',
      'Transfers calls that sound urgent to a clinician immediately',
      'Handles repeat prescription enquiry calls by taking a message',
      'Sends appointment confirmation SMS to every patient booked',
      'Handles parking and location questions',
    ],
    sampleChat: [
      { role: 'caller', text: 'Hi, I need to book an appointment with Dr Chen.' },
      { role: 'agent', text: 'Of course. Are you an existing patient with us?' },
      { role: 'caller', text: "Yes, I've been coming for about two years." },
      { role: 'agent', text: 'Great. Dr Chen has availability Thursday at 10am or Friday at 2pm. Which works better for you?' },
      { role: 'caller', text: 'Thursday at 10 please.' },
      { role: 'agent_upsell', text: "Booked. Is there anything specific you'd like Dr Chen to know before the appointment so we can allow the right amount of time?" },
      { role: 'caller', text: 'Just a follow-up on my blood pressure.' },
      { role: 'agent', text: "Got it. We'll make sure there's enough time. Confirmation SMS coming through now." },
    ],
    heroCTA: 'Hire Grace',
    pricingLink: '/pricing',
  },
  {
    slug: 'sophie',
    name: 'Sophie',
    industry: 'NDIS Providers',
    industrySlug: 'ndis',
    tagline: 'Sophie handles every participant and coordinator call with care and patience.',
    bgColor: '#06B6D4',
    teaserBullets: [
      'Handles participant and support coordinator calls with care',
      'Asks about support type and funding category',
      'Always responds with patience and empathy',
    ],
    knowledgeBullets: [
      'Handles incoming calls from NDIS participants, families, and support coordinators',
      'Asks about the type of support being sought, daily living, community access, support coordination',
      'Always responds with patience, warmth, and zero judgment',
      'Takes detailed messages for any enquiries that need a staff callback',
      'Handles intake enquiries for new participants including contact details and goals',
      'Knows to ask whether the caller is self-managed, plan-managed, or NDIA-managed',
      'Books initial consultation calls for new participants',
      'Never asks for or records sensitive plan or funding details on the call',
      'Handles cancellation or rescheduling of support sessions',
      'Transfers complex or urgent calls to your team immediately',
    ],
    sampleChat: [
      { role: 'caller', text: "Hi, I'm a support coordinator calling about a new participant who needs daily living support." },
      { role: 'agent', text: 'Of course, thank you for calling. Can I get some details about what your participant is looking for?' },
      { role: 'caller', text: "They need about 15 hours a week of personal care support. They're in Southport." },
      { role: 'agent', text: 'Understood. We do provide services in Southport. Are they plan-managed or NDIA-managed?' },
      { role: 'caller', text: 'Plan-managed.' },
      { role: 'agent_upsell', text: 'Perfect. Let me take your details and have our intake coordinator call you back within two business hours to discuss availability and compatibility.' },
      { role: 'caller', text: 'That would be great, thank you.' },
      { role: 'agent', text: 'Happy to help. Can I get your name and best contact number?' },
    ],
    heroCTA: 'Hire Sophie',
    pricingLink: '/pricing',
  },
  {
    slug: 'mia',
    name: 'Mia',
    industry: 'Retail',
    industrySlug: 'retail',
    tagline: 'Mia handles every stock enquiry and customer question while you serve in-store.',
    bgColor: '#F59E0B',
    teaserBullets: [
      'Handles stock enquiries by size, colour, and availability',
      'Takes layby requests and special orders',
      'Answers hours, location, and online order questions',
    ],
    knowledgeBullets: [
      'Handles stock enquiries by product name, size, and colour',
      'Knows to check availability before confirming a hold',
      'Places holds on items for customers calling ahead',
      'Handles layby enquiries and takes initial layby details',
      'Answers opening hours, location, and parking questions',
      'Handles questions about returns and exchange policy',
      'Takes special order requests for out-of-stock items',
      'Handles online order status enquiries and takes details for follow-up',
      'Transfers complex complaints or refund requests to staff',
      'Sends confirmation SMS for any hold or special order placed',
    ],
    sampleChat: [
      { role: 'caller', text: 'Hi, do you have the New Balance 574 in white in a size 10?' },
      { role: 'agent', text: 'Let me check that for you. White with the grey sole or the cream sole?' },
      { role: 'caller', text: 'The grey sole.' },
      { role: 'agent', text: 'We have that in stock in size 10. Would you like me to put a pair aside for you?' },
      { role: 'caller', text: "Yes please, I'll be in this afternoon." },
      { role: 'agent_upsell', text: 'Done. We can hold them until close of business today. Would you also like to know if we have the matching socks in stock?' },
      { role: 'caller', text: 'Ha, sure why not.' },
      { role: 'agent', text: "We do. I'll add a note to hold a pair of those too. What name for the hold?" },
    ],
    heroCTA: 'Hire Mia',
    pricingLink: '/pricing',
  },
  {
    slug: 'james',
    name: 'James',
    industry: 'Professional Services',
    industrySlug: 'professional-services',
    tagline: 'James qualifies new enquiries so you only spend time with the right clients.',
    bgColor: '#374151',
    teaserBullets: [
      'Qualifies new enquiries by matter type before they reach you',
      'Books consultations without giving legal or financial advice',
      'Takes detailed messages for urgent matters',
    ],
    knowledgeBullets: [
      "Asks every new enquiry what type of matter or service they're looking for",
      'Qualifies urgency, is this time-sensitive or a general enquiry',
      'Books initial consultation calls or meetings without giving advice',
      'Takes detailed messages for existing clients with urgent matters',
      'Never gives legal, financial, or professional advice under any circumstances',
      'Handles conflict check requests by taking the relevant party names',
      'Asks whether the caller is a business or individual client',
      'Handles enquiries about fees and billing with "I\'ll have someone call you to discuss that"',
      'Manages appointment confirmations and cancellations',
      'Sends consultation confirmation SMS to every new booking',
    ],
    sampleChat: [
      { role: 'caller', text: 'Hi, I need to speak to a family lawyer about a property settlement.' },
      { role: 'agent', text: 'Of course. To make sure we connect you with the right person, is this related to a separation or divorce?' },
      { role: 'caller', text: 'Yes, we separated about six months ago.' },
      { role: 'agent', text: 'Understood. We have a specialist in family property matters. Would you like to book a 30-minute initial consultation?' },
      { role: 'caller', text: 'Yes, as soon as possible.' },
      { role: 'agent_upsell', text: 'We have availability this Wednesday at 2pm or Thursday at 10am. Which works for you?' },
      { role: 'caller', text: 'Wednesday at 2.' },
      { role: 'agent', text: "Booked. Confirmation coming through now. Is there anything specific you'd like the lawyer to know before the meeting?" },
    ],
    heroCTA: 'Hire James',
    pricingLink: '/pricing',
  },
  {
    slug: 'olivia',
    name: 'Olivia',
    industry: 'Hospitality and Hotels',
    industrySlug: 'hospitality',
    tagline: 'Olivia handles reservations and enquiries so your team can focus on guests.',
    bgColor: '#7C3AED',
    teaserBullets: [
      'Takes room enquiries, reservations, and function bookings',
      'Asks party size, dates, and special requests automatically',
      'Handles cancellations professionally',
    ],
    knowledgeBullets: [
      'Takes room enquiries and handles reservation bookings',
      'Asks party size, check-in date, check-out date, and room preference',
      'Handles function and event enquiry calls with initial details',
      'Takes special request notes, accessibility, dietary, celebrations',
      'Handles cancellation and modification requests',
      'Answers questions about amenities, parking, and pet policies',
      'Handles restaurant reservation calls for in-house dining',
      'Knows to ask about early check-in or late check-out preferences',
      'Takes group booking enquiries and passes them to the reservations team',
      'Sends booking confirmation SMS to every guest',
    ],
    sampleChat: [
      { role: 'caller', text: "Hi, I'd like to make a reservation for Saturday night." },
      { role: 'agent', text: 'Of course! How many guests will be dining?' },
      { role: 'caller', text: 'Four adults.' },
      { role: 'agent', text: 'And do you have a preference for inside or outside seating?' },
      { role: 'caller', text: 'Outside if possible.' },
      { role: 'agent_upsell', text: "We'll do our best. Is this a special occasion? We can arrange a complimentary dessert plate if you'd like to let us know." },
      { role: 'caller', text: "It's my wife's birthday actually." },
      { role: 'agent', text: "How lovely! I'll add that note. What name for the reservation and your mobile for confirmation?" },
    ],
    heroCTA: 'Hire Olivia',
    pricingLink: '/pricing',
  },
  {
    slug: 'mitch',
    name: 'Mitch',
    industry: 'Automotive',
    industrySlug: 'automotive',
    tagline: "Mitch books services and handles parts enquiries while you're in the workshop.",
    bgColor: '#DC2626',
    teaserBullets: [
      'Books logbook services, roadworthys, and repairs',
      'Asks vehicle make, model, year, and kilometre reading',
      'Handles parts enquiries and service pricing questions',
    ],
    knowledgeBullets: [
      'Books logbook services, roadworthy certificates, and general repairs',
      'Asks vehicle make, model, year, and current kilometre reading on every call',
      'Knows common service types and their approximate durations for scheduling',
      'Handles tyre fitting, brake pad, battery, and wheel alignment bookings',
      'Takes parts enquiry details including part name and vehicle details',
      'Handles "how much does a service cost" with accurate range responses',
      'Sends booking confirmation SMS to every customer',
      'Handles courtesy car enquiries by checking availability',
      'Manages cancellation and rescheduling calls',
      'Asks about warning lights or specific symptoms before booking',
    ],
    sampleChat: [
      { role: 'caller', text: 'Hi, I need to book my car in for a service.' },
      { role: 'agent', text: 'Of course. What make and model is the vehicle?' },
      { role: 'caller', text: '2021 Toyota RAV4.' },
      { role: 'agent', text: "And roughly what's the current odometer reading?" },
      { role: 'caller', text: 'About 42,000 kilometres.' },
      { role: 'agent_upsell', text: "At 42,000 that's due for a logbook service. We can also do a brake inspection at the same time as a precaution, would you like to include that?" },
      { role: 'caller', text: 'Yeah sounds good.' },
      { role: 'agent', text: 'Great. We have availability Thursday morning or Friday afternoon. Which suits?' },
    ],
    heroCTA: 'Hire Mitch',
    pricingLink: '/pricing',
  },
  {
    slug: 'zara',
    name: 'Zara',
    industry: 'Beauty and Wellness',
    industrySlug: 'beauty',
    tagline: 'Zara keeps your appointment book full without you stopping mid-treatment.',
    bgColor: '#D97706',
    teaserBullets: [
      'Books appointments by service type and preferred therapist',
      'Knows treatment durations for accurate scheduling',
      'Handles cancellation policy questions',
    ],
    knowledgeBullets: [
      'Books appointments by service type, duration, and preferred therapist',
      'Knows treatment durations for accurate scheduling, no double-booking',
      'Handles colour, cut, treatment, and nail appointment bookings',
      'Asks about new vs returning client and any relevant history',
      'Handles cancellation policy questions professionally',
      'Takes new client details including any sensitivities or allergies',
      'Manages cancellations and reschedules with rebooking prompts',
      'Handles gift voucher enquiries',
      'Sends appointment confirmation SMS to every booking',
      'Handles parking and location questions',
    ],
    sampleChat: [
      { role: 'caller', text: "Hi, I'd like to book in for a colour and cut." },
      { role: 'agent', text: 'Of course! Have you been in with us before?' },
      { role: 'caller', text: 'Yes, I usually see Emma.' },
      { role: 'agent', text: 'Emma has availability next Tuesday at 11am or Thursday at 2pm. Which works?' },
      { role: 'caller', text: 'Tuesday at 11.' },
      { role: 'agent_upsell', text: "Perfect. For a colour and cut I'll allow 2.5 hours. Would you like to add a treatment? Emma often recommends one after colour to keep hair healthy." },
      { role: 'caller', text: 'Sure, add that in.' },
      { role: 'agent', text: "Done. Confirmation SMS on its way. Is there anything Emma should know, any new colour direction you're thinking?" },
    ],
    heroCTA: 'Hire Zara',
    pricingLink: '/pricing',
  },
  {
    slug: 'ryan',
    name: 'Ryan',
    industry: 'Fitness and Gyms',
    industrySlug: 'fitness',
    tagline: 'Ryan handles every enquiry so your staff can focus on members on the floor.',
    bgColor: '#16A34A',
    teaserBullets: [
      'Handles membership enquiries and class bookings',
      'Books intro sessions and personal training consultations',
      'Handles cancellation and freeze requests',
    ],
    knowledgeBullets: [
      'Handles membership enquiries including plan types and pricing',
      'Books intro sessions and gym tours for new members',
      'Books group fitness classes and personal training sessions',
      'Handles membership pause, cancellation, and upgrade requests',
      'Answers questions about class timetable and availability',
      'Takes enquiries about corporate memberships and group deals',
      'Handles lost property and facility enquiries',
      'Knows to ask about fitness goals for personal training bookings',
      'Sends booking confirmation SMS to every new booking',
      'Handles joining fee waiver and promotional enquiries',
    ],
    sampleChat: [
      { role: 'caller', text: "Hi, I'm interested in joining the gym." },
      { role: 'agent', text: 'Great, welcome! Have you visited us before or would you like to come in for a tour first?' },
      { role: 'caller', text: "I'd like to come in and have a look." },
      { role: 'agent', text: 'Of course. We can book you in for a free tour and a quick chat with one of our team. When suits you?' },
      { role: 'caller', text: 'Maybe this Saturday morning?' },
      { role: 'agent_upsell', text: "Saturday at 9am works perfectly. Can I also book you a complimentary 30-minute intro session with a trainer while you're here? It's a great way to see if we're the right fit." },
      { role: 'caller', text: 'Yeah that sounds good.' },
      { role: 'agent', text: "Excellent. What are your main fitness goals? I'll match you with the right trainer." },
    ],
    heroCTA: 'Hire Ryan',
    pricingLink: '/pricing',
  },
  {
    slug: 'lily',
    name: 'Lily',
    industry: 'Education and Tutoring',
    industrySlug: 'education',
    tagline: 'Lily handles every parent enquiry so you can focus on teaching.',
    bgColor: '#2563EB',
    teaserBullets: [
      'Handles enrolment enquiries and books trial lessons',
      'Asks for student year level and subjects needed',
      'Takes parent contact details for follow-up',
    ],
    knowledgeBullets: [
      'Handles enrolment enquiries and books trial lessons',
      'Asks for student year level, school, and subjects needing support',
      'Captures parent contact details and preferred lesson times',
      'Handles questions about tutoring approach and qualifications',
      'Books school holiday program places',
      'Handles sibling enrolment enquiries efficiently',
      'Takes enquiries about online vs in-person options',
      'Handles payment plan enquiries by taking details for a callback',
      'Sends trial lesson confirmation SMS to every new booking',
      'Manages lesson cancellations and reschedule requests',
    ],
    sampleChat: [
      { role: 'caller', text: "Hi, I'm looking for a maths tutor for my daughter." },
      { role: 'agent', text: 'Of course. What year is she in?' },
      { role: 'caller', text: "She's in Year 9." },
      { role: 'agent', text: "Year 9 maths, we can definitely help with that. Is this for general support or is there a specific exam or topic she's finding difficult?" },
      { role: 'caller', text: "She's really struggling with algebra." },
      { role: 'agent_upsell', text: "That's one of our most common Year 9 requests. Would you like to book a free 30-minute trial lesson so she can meet the tutor before committing?" },
      { role: 'caller', text: 'Yes that would be great.' },
      { role: 'agent', text: 'Wonderful. What days and times generally work for her after school?' },
    ],
    heroCTA: 'Hire Lily',
    pricingLink: '/pricing',
  },
]

export function getReceptionist(slug: string): Receptionist | undefined {
  return RECEPTIONISTS.find(r => r.slug === slug)
}

// Map an industry slug (as used in /industries/[slug]) to the matching
// receptionist. Used by the avatar card injected onto each industry page.
export function receptionistForIndustry(industrySlug: string): Receptionist | undefined {
  return RECEPTIONISTS.find(r => r.industrySlug === industrySlug)
}
